# .streamlit/secrets.toml

[connections.snowflake]
account = "vz31470.west-europe.azure" #No https in the accoutn
user = "HR"
password = "hrPassword123"
role = "REPORTING"
warehouse = "COMPUTE_WH"
database = "HR"
schema = "LKDN_LICENSES"
client_session_keep_alive = true